development:
  type: swift
  opts:
    username: test:tester
    api_key: testing
    auth_method: password
    auth_url: http://192.168.33.50:12345/auth/v1.0
    service_type: object-store
    container_name: cram

production:
  type: swift
  opts:
    username: test:tester
    api_key: testing
    auth_method: password
    auth_url: http://swift:8080/auth/v1.0
    service_type: object-store
    container_name: cram

test:
  type: file
  opts:
    base_directory: filestorage_test
