sudo: required

language: ruby

services:
  - docker

before_install:
  - docker-compose -f docker-compose_dev.yml up -d
script:
  - cd webapp
  - bundle install
  - bundle exec rake test
env:
  - DOCKER_HOST_IP=127.0.0.1

