mongo:
  image: mongo:3.1.4
  ports:
    - "27017"
    - "28017"
  command: mongod --rest --httpinterface
  volumes:
    - ./data/db:/data/db
mongobackup:
  image: ihgs/mongodump:3.1.4
  environment:
    - 'CRON_SCHEDULE=0 1 * * *'
  volumes:
    - ./backup:/backup
  links:
    - mongo
web:
  build: .
  environment:
    - RAILS_ENV=production
    - SECRET_KEY_BASE=ghaoi217gbganpgriohg9priahgug0ehhuohqaonv9uaz
    - RAILS_SERVE_STATIC_FILES=true
  volumes:
    - ./log:/webapp/log
  ports:
    - "3000:3000"
  links:
    - mongo
    - swift
munin:
  image: ihgs/munin-master:latest
  ports:
    - "8090:80"
  volumes:
    - ./munin/log:/var/log/munin
    - ./munin/lib:/var/lib/munin
    - ./munin/munin-conf.d:/etc/munin/munin-conf.d

swift:
  image: serverascode/swift-onlyone
  ports:
    - "8080"
  volumes_from:
    - swift_data

swift_data:
  image: busybox
  volumes:
    - ./swift:/srv
