mongo:
  image: mongo:3.1.4
  ports:
    - "27017:27017"
    - "28017:28017"
  command: mongod --rest --httpinterface
  volumes:
    - /etc/localtime:/etc/localtime:ro

swift:
  image: morrisjobke/docker-swift-onlyone
  ports:
    - "12345:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - swift_data

swift_data:
  image: busybox
  volumes:
    - ./swift_dev:/var/srv
    - /etc/localtime:/etc/localtime:ro
  tty: true
