mongo:
  image: mongo:3.1.4
  ports:
    - "27017"
    - "28017"
  command: mongod --rest --httpinterface
  volumes:
    - ./data/db:/data/db
web:
  build: .
  environment:
    - RAILS_ENV=production
    - SECRET_KEY_BASE=ghaoi217gbganpgriohg9priahgug0ehhuohqaonv9uaz
    - RAILS_SERVE_STATIC_FILES=true
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - ./log:/webapp/log
  ports:
    - "3000:3000"
  links:
    - mongo

munin:
  image: ihgs/munin-master:latest
  ports:
    - "8090:80"
  volumes:
    - ./munin/log:/var/log/munin
    - ./munin/lib:/var/lib/munin
    - ./munin/munin-conf.d:/etc/munin/munin-conf.d
